-💛 hi, i’m rin / ena /nene. . .

-🤍 i’m currently interested in milgram , pjsk(jp/chn) , good night world. . .

-🌱 i’m learning chinese , spanish and swedish . . .

-💞️ silly (15). . .

-💌 how to reach me..ds:ffuutq.kajiyamq , ig:ffuuta.kajiyamq , pinterest:apwapwapwpa , tiktok:fuuta.kajiyamq . . .

-💟 top kins _; ena , akito , nene (yashiro+kusanagi) , ichi (good night,world) , sayu , sucrose , noé . . .

-🔆 suspected autism . . .

-〰basic dni criteria. . . dazai/rui fans. . .

-💦i make kms/kys jokes . . .

-💫i get mad/angry/sad randomly. have patience lmao . . . 

-🔸<akito shinonome3

-🟡mikofuu #1 lover !

-💤 silly friends mention_; azul , axel , kara , cherie , ellie , hayn . . .

-🍓 cosplays_; nene yashiro , toya aoyagi . . . 

-🌼fandoms_; milgram , pjsk(jp/chn) , vnc , bsd , gnw , crk , genshin , hsr , hi3 , she-ra , lwa , horimiya , sk8 , etc . . . 
